/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as lendingPlatformSol from "./LendingPlatform.sol";
export type { lendingPlatformSol };
export type { LendingToken } from "./LendingToken";
export type { MockOracle } from "./MockOracle";
