import { ethers, artifacts } from "hardhat";
import * as fs from "fs";
import * as path from "path";

async function main() {
  const [deployer] = await ethers.getSigners();
  console.log("🚀 Deploying with account:", deployer.address);

  // 1. Deploy Mock Oracle
  const MockOracle = await ethers.getContractFactory("MockOracle");
  const oracle = await MockOracle.deploy(8, 200000000000); 
  await oracle.waitForDeployment();
  const oracleAddress = await oracle.getAddress();
  console.log("✅ MockOracle deployed to:", oracleAddress);

  // 2. Deploy Lending Token (DUSD)
  const LendingToken = await ethers.getContractFactory("LendingToken");
  const token = await LendingToken.deploy();
  await token.waitForDeployment();
  const tokenAddress = await token.getAddress();
  console.log("✅ LendingToken deployed to:", tokenAddress);

  // 3. Deploy Platform
  const LendingPlatform = await ethers.getContractFactory("LendingPlatform");
  const platform = await LendingPlatform.deploy(tokenAddress, oracleAddress);
  await platform.waitForDeployment();
  const platformAddress = await platform.getAddress();
  console.log("✅ LendingPlatform deployed to:", platformAddress);

  // --- SEED DATA ---
  const txMint = await token.faucet();
  await txMint.wait();
  const txApprove = await token.approve(platformAddress, ethers.parseEther("10000"));
  await txApprove.wait();
  console.log("💧 Seeded deployer with 1000 DUSD");

  // --- AUTOMATIC FRONTEND CONFIGURATION ---
  console.log("📝 Writing to Frontend constants...");

  // Get Artifacts (ABIs)
  const PlatformArtifact = await artifacts.readArtifact("LendingPlatform");
  const TokenArtifact = await artifacts.readArtifact("LendingToken");
  const OracleArtifact = await artifacts.readArtifact("MockOracle");

  // Construct the file content
  const fileContent = `/* 
  AUTOGENERATED FILE - DO NOT EDIT MANUALLY
  Generated by: backend/scripts/deploy.ts
  Date: ${new Date().toISOString()}
*/

export const PLATFORM_ADDRESS = "${platformAddress}";
export const TOKEN_ADDRESS = "${tokenAddress}";
export const ORACLE_ADDRESS = "${oracleAddress}";

export const PLATFORM_ABI_ARRAY = ${JSON.stringify(PlatformArtifact.abi, null, 2)} as const;

export const TOKEN_ABI = ${JSON.stringify(TokenArtifact.abi, null, 2)} as const;

export const ORACLE_ABI = ${JSON.stringify(OracleArtifact.abi, null, 2)} as const;
`;

  // Write to frontend
  const frontendPath = path.join(__dirname, "../../frontend/src/lib/constants.ts");
  
  // Ensure directory exists
  const dir = path.dirname(frontendPath);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }

  fs.writeFileSync(frontendPath, fileContent);
  console.log(`✨ Config written to: ${frontendPath}`);
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});