/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface LendingPlatformInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "BASE_COLLATERAL_RATIO"
      | "MIN_COLLATERAL_RATIO"
      | "createLoanRequest"
      | "fundLoan"
      | "getEthPrice"
      | "getRequiredCollateralRatio"
      | "lendingToken"
      | "liquidate"
      | "loanCounter"
      | "loans"
      | "priceFeed"
      | "repayLoan"
      | "reputation"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CollateralLiquidated"
      | "LoanFunded"
      | "LoanRepaid"
      | "LoanRequested"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "BASE_COLLATERAL_RATIO",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_COLLATERAL_RATIO",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "createLoanRequest",
    values: [BigNumberish, BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "fundLoan",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEthPrice",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRequiredCollateralRatio",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lendingToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "liquidate",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "loanCounter",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "loans", values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: "priceFeed", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "repayLoan",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "reputation",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "BASE_COLLATERAL_RATIO",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MIN_COLLATERAL_RATIO",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createLoanRequest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "fundLoan", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getEthPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRequiredCollateralRatio",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lendingToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "liquidate", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "loanCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "loans", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "priceFeed", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "repayLoan", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "reputation", data: BytesLike): Result;
}

export namespace CollateralLiquidatedEvent {
  export type InputTuple = [id: BigNumberish, liquidator: AddressLike];
  export type OutputTuple = [id: bigint, liquidator: string];
  export interface OutputObject {
    id: bigint;
    liquidator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LoanFundedEvent {
  export type InputTuple = [id: BigNumberish, lender: AddressLike];
  export type OutputTuple = [id: bigint, lender: string];
  export interface OutputObject {
    id: bigint;
    lender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LoanRepaidEvent {
  export type InputTuple = [id: BigNumberish, borrower: AddressLike];
  export type OutputTuple = [id: bigint, borrower: string];
  export interface OutputObject {
    id: bigint;
    borrower: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LoanRequestedEvent {
  export type InputTuple = [
    id: BigNumberish,
    borrower: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [id: bigint, borrower: string, amount: bigint];
  export interface OutputObject {
    id: bigint;
    borrower: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface LendingPlatform extends BaseContract {
  connect(runner?: ContractRunner | null): LendingPlatform;
  waitForDeployment(): Promise<this>;

  interface: LendingPlatformInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  BASE_COLLATERAL_RATIO: TypedContractMethod<[], [bigint], "view">;

  MIN_COLLATERAL_RATIO: TypedContractMethod<[], [bigint], "view">;

  createLoanRequest: TypedContractMethod<
    [
      _amountToBorrow: BigNumberish,
      _interest: BigNumberish,
      _duration: BigNumberish,
      _ipfsHash: string
    ],
    [void],
    "payable"
  >;

  fundLoan: TypedContractMethod<[_loanId: BigNumberish], [void], "nonpayable">;

  getEthPrice: TypedContractMethod<[], [bigint], "view">;

  getRequiredCollateralRatio: TypedContractMethod<
    [_user: AddressLike],
    [bigint],
    "view"
  >;

  lendingToken: TypedContractMethod<[], [string], "view">;

  liquidate: TypedContractMethod<[_loanId: BigNumberish], [void], "nonpayable">;

  loanCounter: TypedContractMethod<[], [bigint], "view">;

  loans: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        boolean,
        string,
        string
      ] & {
        id: bigint;
        borrower: string;
        lender: string;
        amount: bigint;
        collateralAmount: bigint;
        interest: bigint;
        startTime: bigint;
        duration: bigint;
        active: boolean;
        funded: boolean;
        ipfsHash: string;
        loanAgreementHash: string;
      }
    ],
    "view"
  >;

  priceFeed: TypedContractMethod<[], [string], "view">;

  repayLoan: TypedContractMethod<[_loanId: BigNumberish], [void], "nonpayable">;

  reputation: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "BASE_COLLATERAL_RATIO"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_COLLATERAL_RATIO"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "createLoanRequest"
  ): TypedContractMethod<
    [
      _amountToBorrow: BigNumberish,
      _interest: BigNumberish,
      _duration: BigNumberish,
      _ipfsHash: string
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "fundLoan"
  ): TypedContractMethod<[_loanId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getEthPrice"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getRequiredCollateralRatio"
  ): TypedContractMethod<[_user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "lendingToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "liquidate"
  ): TypedContractMethod<[_loanId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "loanCounter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "loans"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        boolean,
        string,
        string
      ] & {
        id: bigint;
        borrower: string;
        lender: string;
        amount: bigint;
        collateralAmount: bigint;
        interest: bigint;
        startTime: bigint;
        duration: bigint;
        active: boolean;
        funded: boolean;
        ipfsHash: string;
        loanAgreementHash: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "priceFeed"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "repayLoan"
  ): TypedContractMethod<[_loanId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "reputation"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  getEvent(
    key: "CollateralLiquidated"
  ): TypedContractEvent<
    CollateralLiquidatedEvent.InputTuple,
    CollateralLiquidatedEvent.OutputTuple,
    CollateralLiquidatedEvent.OutputObject
  >;
  getEvent(
    key: "LoanFunded"
  ): TypedContractEvent<
    LoanFundedEvent.InputTuple,
    LoanFundedEvent.OutputTuple,
    LoanFundedEvent.OutputObject
  >;
  getEvent(
    key: "LoanRepaid"
  ): TypedContractEvent<
    LoanRepaidEvent.InputTuple,
    LoanRepaidEvent.OutputTuple,
    LoanRepaidEvent.OutputObject
  >;
  getEvent(
    key: "LoanRequested"
  ): TypedContractEvent<
    LoanRequestedEvent.InputTuple,
    LoanRequestedEvent.OutputTuple,
    LoanRequestedEvent.OutputObject
  >;

  filters: {
    "CollateralLiquidated(uint256,address)": TypedContractEvent<
      CollateralLiquidatedEvent.InputTuple,
      CollateralLiquidatedEvent.OutputTuple,
      CollateralLiquidatedEvent.OutputObject
    >;
    CollateralLiquidated: TypedContractEvent<
      CollateralLiquidatedEvent.InputTuple,
      CollateralLiquidatedEvent.OutputTuple,
      CollateralLiquidatedEvent.OutputObject
    >;

    "LoanFunded(uint256,address)": TypedContractEvent<
      LoanFundedEvent.InputTuple,
      LoanFundedEvent.OutputTuple,
      LoanFundedEvent.OutputObject
    >;
    LoanFunded: TypedContractEvent<
      LoanFundedEvent.InputTuple,
      LoanFundedEvent.OutputTuple,
      LoanFundedEvent.OutputObject
    >;

    "LoanRepaid(uint256,address)": TypedContractEvent<
      LoanRepaidEvent.InputTuple,
      LoanRepaidEvent.OutputTuple,
      LoanRepaidEvent.OutputObject
    >;
    LoanRepaid: TypedContractEvent<
      LoanRepaidEvent.InputTuple,
      LoanRepaidEvent.OutputTuple,
      LoanRepaidEvent.OutputObject
    >;

    "LoanRequested(uint256,address,uint256)": TypedContractEvent<
      LoanRequestedEvent.InputTuple,
      LoanRequestedEvent.OutputTuple,
      LoanRequestedEvent.OutputObject
    >;
    LoanRequested: TypedContractEvent<
      LoanRequestedEvent.InputTuple,
      LoanRequestedEvent.OutputTuple,
      LoanRequestedEvent.OutputObject
    >;
  };
}
