/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type {
  Signer,
  BigNumberish,
  ContractDeployTransaction,
  ContractRunner,
} from "ethers";
import type { NonPayableOverrides } from "../../common";
import type {
  MockOracle,
  MockOracleInterface,
} from "../../contracts/MockOracle";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint8",
        name: "decimals_",
        type: "uint8",
      },
      {
        internalType: "int256",
        name: "initialPrice",
        type: "int256",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [],
    name: "decimals",
    outputs: [
      {
        internalType: "uint8",
        name: "",
        type: "uint8",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "latestRoundData",
    outputs: [
      {
        internalType: "uint80",
        name: "roundId",
        type: "uint80",
      },
      {
        internalType: "int256",
        name: "answer",
        type: "int256",
      },
      {
        internalType: "uint256",
        name: "startedAt",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "updatedAt",
        type: "uint256",
      },
      {
        internalType: "uint80",
        name: "answeredInRound",
        type: "uint80",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "int256",
        name: "newPrice",
        type: "int256",
      },
    ],
    name: "updatePrice",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b50604051610378380380610378833981810160405281019061003291906100cf565b81600160006101000a81548160ff021916908360ff16021790555080600081905550505061010f565b600080fd5b600060ff82169050919050565b61007681610060565b811461008157600080fd5b50565b6000815190506100938161006d565b92915050565b6000819050919050565b6100ac81610099565b81146100b757600080fd5b50565b6000815190506100c9816100a3565b92915050565b600080604083850312156100e6576100e561005b565b5b60006100f485828601610084565b9250506020610105858286016100ba565b9150509250929050565b61025a8061011e6000396000f3fe608060405234801561001057600080fd5b50600436106100415760003560e01c8063313ce56714610046578063d4c19bda14610064578063feaf968c14610080575b600080fd5b61004e6100a2565b60405161005b9190610101565b60405180910390f35b61007e60048036038101906100799190610157565b6100b9565b005b6100886100c3565b6040516100999594939291906101d1565b60405180910390f35b6000600160009054906101000a900460ff16905090565b8060008190555050565b6000806000806000806000546000426000945094509450945094509091929394565b600060ff82169050919050565b6100fb816100e5565b82525050565b600060208201905061011660008301846100f2565b92915050565b600080fd5b6000819050919050565b61013481610121565b811461013f57600080fd5b50565b6000813590506101518161012b565b92915050565b60006020828403121561016d5761016c61011c565b5b600061017b84828501610142565b91505092915050565b600069ffffffffffffffffffff82169050919050565b6101a381610184565b82525050565b6101b281610121565b82525050565b6000819050919050565b6101cb816101b8565b82525050565b600060a0820190506101e6600083018861019a565b6101f360208301876101a9565b61020060408301866101c2565b61020d60608301856101c2565b61021a608083018461019a565b969550505050505056fea2646970667358221220c406eded9871954b3e3167f7604b3302d0b037709a7738e8e749032a2fe240b564736f6c63430008140033";

type MockOracleConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: MockOracleConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class MockOracle__factory extends ContractFactory {
  constructor(...args: MockOracleConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    decimals_: BigNumberish,
    initialPrice: BigNumberish,
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(decimals_, initialPrice, overrides || {});
  }
  override deploy(
    decimals_: BigNumberish,
    initialPrice: BigNumberish,
    overrides?: NonPayableOverrides & { from?: string }
  ) {
    return super.deploy(decimals_, initialPrice, overrides || {}) as Promise<
      MockOracle & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): MockOracle__factory {
    return super.connect(runner) as MockOracle__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): MockOracleInterface {
    return new Interface(_abi) as MockOracleInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): MockOracle {
    return new Contract(address, _abi, runner) as unknown as MockOracle;
  }
}
